### ISSUE TITLE
Spelling of access file is wrong

### ISSUE THREAD

**Issue by risan-raja** [intel/vscode-oneapi-devcloud-connector#5]
https://github.com/intel/vscode-oneapi-devcloud-connector/blob/e9a56452b0a20d4fc11d187ed9c6f48cd1f23aa1/src/utils/ssh_config.ts#L51

**Comment by amakarev** [comment]
@risan-raja Thank you for you feed back. I don't see anything wrong here. This line creates a path to a copy of the script that will be created later, so it doesn't really matter how it is named. This is done because cygwin only sees its own file system, so we copy this script there so that it can be run from the cygwin terminal
